// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type SearchRequest struct {
	OrderID string `form:"orderID"`
}

type SearchResponse struct {
	OrderID    string `json:"orderID"`
	Status     int    `json:"status"`
	Username   string `json:"username"`
	TradeID    string `json:"tradeID"`
	PayChannel int    `json:"pay_channel"`
	PayAmount  int    `json:"pay_amount"`
	PayTime    int    `json:"pay_time"`
}
