// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type Request struct {
	Name string `path:"name,options=you|me|ysh"`
}

type Response struct {
	Message string `json:"message"`
}
