// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message      string `json:"message"`
	AccessToken  string `json:"accsee_token"`
	AccseeExpire int    `json:"access_expire"`
	RefreshAfter int    `json:"refreshAfter"`
}

type SignupRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
	Gender     int    `json:"gender, options=0|1|2, default=0"`
}

type SingupResponse struct {
	Message string `json:"message"`
}

type UserInfoRequest struct {
	UserId int64 `form:"user_id"`
}

type UserInfoResponse struct {
	UserName string `json:"username"`
	Gender   int    `json:"gender"`
	Message  string `json:"message"`
}
