// 版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        v5.29.3
// source: proto/add.proto

// 包名

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息请求
type AddResquest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *AddResquest) Reset() {
	*x = AddResquest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_add_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResquest) ProtoMessage() {}

func (x *AddResquest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_add_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResquest.ProtoReflect.Descriptor instead.
func (*AddResquest) Descriptor() ([]byte, []int) {
	return file_proto_add_proto_rawDescGZIP(), []int{0}
}

func (x *AddResquest) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AddResquest) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply int64 `protobuf:"varint,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_add_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_add_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_add_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetReply() int64 {
	if x != nil {
		return x.Reply
	}
	return 0
}

var File_proto_add_proto protoreflect.FileDescriptor

var file_proto_add_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x29, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79,
	0x22, 0x23, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x34, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x12, 0x29, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x79, 0x73, 0x68, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x61, 0x64, 0x64, 0x5f, 0x63, 0x6c, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_add_proto_rawDescOnce sync.Once
	file_proto_add_proto_rawDescData = file_proto_add_proto_rawDesc
)

func file_proto_add_proto_rawDescGZIP() []byte {
	file_proto_add_proto_rawDescOnce.Do(func() {
		file_proto_add_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_add_proto_rawDescData)
	})
	return file_proto_add_proto_rawDescData
}

var file_proto_add_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_add_proto_goTypes = []interface{}{
	(*AddResquest)(nil), // 0: pb.AddResquest
	(*AddResponse)(nil), // 1: pb.AddResponse
}
var file_proto_add_proto_depIdxs = []int32{
	0, // 0: pb.Gretter.Add:input_type -> pb.AddResquest
	1, // 1: pb.Gretter.Add:output_type -> pb.AddResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_add_proto_init() }
func file_proto_add_proto_init() {
	if File_proto_add_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_add_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResquest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_add_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_add_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_add_proto_goTypes,
		DependencyIndexes: file_proto_add_proto_depIdxs,
		MessageInfos:      file_proto_add_proto_msgTypes,
	}.Build()
	File_proto_add_proto = out.File
	file_proto_add_proto_rawDesc = nil
	file_proto_add_proto_goTypes = nil
	file_proto_add_proto_depIdxs = nil
}
