// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type SignupRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   string `json:"gender, options=male|female|secret, default=secret"`
}

type SingupResponse struct {
	Message string `json:"message"`
}
